### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by ejwill04** [dylanavery720/markostractions-#11]
- I like that PR messages and the back-and-forth.
- devin_tuesday as a branch name?  
- webpack-try - is this a WIP? 
- how do I interpret the hospital emoji in the web pack try PR? 🏥

**Comment by devinmarieb** [comment]
Enhancement:

will be more specific with branch names when we are working on actual issues not just playing around.

webpack try was when we were considering using webpack instead of the suggested lasso. we have since moved back to lasso.

it's a love hotel, not a hospital. marko and electron are making love apparently... according to Dylan.

**Comment by dylanavery720** [comment]
@ejwill04 it a LOVE HOTEL 🏩  for Marko and Electron.
